nota1=float(input("digite tua nota: "))
nota2=float(input("digite a segunda nota: "))
nota3=float(input("digite a terceira nota: "))
nota4=float(input("digite a quarta nota: "))
mediaDasNotas=float((nota1 + nota2 + nota3 + nota4)/4)
print("a mdeia das suas notas é: " + str(mediaDasNotas))